### ISSUE TITLE
Substitutes for MOSFET

### ISSUE THREAD

**Issue by coredump4** [linker3000/shukran#3]
My preferred electronics supplier is out of the IRLML6402 for many months.

Would [this one](https://www.digikey.com/en/products/detail/SI2323DS-T1-E3/SI2323DS-T1-E3CT-ND/1656850?utm_medium=email&utm_source=oce&utm_campaign=4251_OCE21RT&utm_content=productdetail_US&utm_cid=487557&so=68045690&mkt_tok=eyJpIjoiTkRRMVpEQTBObUl5TTJVeCIsInQiOiI1VDkzVk1qV3JlS0lENFpLR2tSUVwvRkx6dURBZjNCMUY1Z0UyUTJMb2V1WHBxZDNmZ1NSMGlEYzhYV0laQmtcL1BXN3dNNTFISlpqcTVBWFwvODAwNDE5YnptajFYc01wbStabjZMVmVxa0tnVEtrOXZNSFZHaW1CZ2p4d3MwcmRRciJ9) work instead?  It's similar but doesn't match up with the suggested one perfectly.  If that one is not suitable, can you suggest others?

Thanks

**Comment by linker3000** [comment]
Wow, really sorry I missed this coming in for so long.

Checking the specs, yes, that MOSFET should be fine.
