### ISSUE TITLE
CJMCU-232H Schematic

### ISSUE THREAD

**Issue by Xylopyrographer** [linker3000/shukran#4]
Nice work indeed. Thank-you.

Would have a link for the schematic of the CJMCU-232H board?

**Comment by linker3000** [comment]
Sorry I don't. It's based on the reference design in the FTDI data sheet for the chip so check that out.

**Comment by Xylopyrographer** [comment]
Timing is everything 😄. After a _lot_ of hunting, finally found it. A version corrected to match the hardware I've got is here:

https://github.com/Xylopyrographer/BitsNThings/blob/main/CJMCU-232H/CJMCU-FT232H%20Schematic%20R1.pdf
